### ISSUE TITLE
[ FR ] Support of Mobile

### ISSUE THREAD

**Issue by StefanoRausch** [valteriomon/obsidian-rapid-notes#1]
Do you have any plans to support the mobile app?

**Comment by valteriomon** [comment]
I didn't know mobile support required anything different, I'll check it out!

**Comment by valteriomon** [comment]
I tested the plugin in the Android app and seems to be working fine, did you encounter any issue?

**Comment by StefanoRausch** [comment]
I have it installed, but I cannot enable it. There might be some flag to activate the mobile support.

**Comment by valteriomon** [comment]
do you have other plugins working on the mobile app? which platform and version of the app are you using? I could not reproduce the issue on Android at least

**Comment by StefanoRausch** [comment]
I am on iOS and iPadOS and have the latest insider build [ with canvas ].

Obsidian fails to load the plugin.
![F1D439A3-B3C9-4C8C-80C9-11FE2F045EEB](https://user-images.githubusercontent.com/1460531/213384357-f9d4c0bd-239e-48ad-aed8-352b4aba9cca.png)

**Comment by wallypg** [comment]
Closing this as I tested on iOS 16.4.1 and it's working without any issue, but I removed in version 1.2.0 the look behind in regular expressions that was causing the issue.

**Comment by valteriomon** [comment]
Closing this as I tested on iOS 16.4.1 and it's working without any issue, but I removed in version 1.2.0 the look behind in regular expressions that was causing the issue.

**Comment by StefanoRausch** [comment]
Thank you, it works!
