### ISSUE TITLE
[feature request] prefix for daily note

### ISSUE THREAD

**Issue by pcause** [valteriomon/obsidian-rapid-notes#3]
can you add a prefix that will open today's daily note.

**Comment by valteriomon** [comment]
I can look into that! but doesn't it make more sense to create a shortcut linked to the command "open today's note" from the palette? why would you open the "create note" modal to type a letter to then open the daily note? not sure I see the benefit of that, but I'm open to do it if I understand the use case

**Comment by pcause** [comment]
just maes it quicker/fewer keystrokes.  but not a huge deal.  found a way to get this done via quickadd, so i'll close this
